version: 2.1

job-template: &job-template
  steps:
    - checkout

    # Install system dependencies
    - run: sudo apt-get update
    - run: sudo apt-get install libuv1-dev

    # Install PHP dependencies
    - run: if [[ "$TYPE" = "git" ]]; then git clone https://www.github.com/bwoebi/php-uv && cd php-uv && phpize && ./configure && make && sudo -E make install; else sudo -E pecl install uv-beta; fi
    #- run: sudo -E pecl install pcov

    # Add extensions to php.ini
    - run: sudo -E docker-php-ext-enable uv
    #- run: sudo -E docker-php-ext-enable pcov

    # Download and cache dependencies
    - restore_cache:
        keys:
          - dependencies

    - run: composer install --no-interaction
    #- run: composer require --dev pcov/clobber && vendor/bin/pcov clobber

    - save_cache:
        key: dependencies
        paths:
          - $HOME/.composer/cache/files

    - run: php -v
    - run: mkdir test-results
    - run: vendor/bin/phpunit --configuration phpunit.xml.dist --log-junit test-results/junit-report.xml --coverage-text
    - store_test_results:
        path: test-results

job-template-win: &job-template-win
  shell: powershell.exe
  steps:
    - checkout
    
     # install system dependencies
    - if ($env:PHP_TYPE -imatch "ts") { choco install php --package-parameters='"/ThreadSafe "' } else { choco install php }
    - choco install composer
    - export PATH="$(powershell -Command '("Process", "Machine" | % { [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", "" } | Select -Unique | % { cygpath $_ }) -Join ":"')"

    # install PHP dependencies
    - $pecl_url = Join-Path "https://windows.php.net/downloads/pecl/releases/uv/0.2.4/php_uv-0.2.4-7.4-" $env:PHP_TYPE "-vc15-x64.zip"
    - Invoke-WebRequest -Uri $pecl_url -OutFile .\uv.zip
    - Expand-Archive .\uv.zip -Destination .\uv
    - Move-Item -Path .\uv\libuv.dll -Destination C:\Windows\System32\libuv.dll
    - Move-Item -Path .\uv\php_uv.dll -Destination C:\ProgramData\chocolatey\php\ext\php_uv.dll
    
    # Add extensions to php.ini
    - Add-Content C:\ProgramData\chocolatey\php\php.ini "`nextension=uv"
    
    # Download and cache dependencies
    - restore_cache:
        keys:
          - dependencies

    - run: composer install --no-interaction
    #- run: composer require --dev pcov/clobber && vendor\bin\pcov clobber

    - save_cache:
        key: dependencies
        paths:
          - $HOME/.composer/cache/files

    - run: php.exe -v
    - run: mkdir test-results
    - run: vendor\bin\phpunit --configuration phpunit.xml.dist --log-junit test-results\junit-report.xml --coverage-text
    - store_test_results:
        path: test-results

orbs:
  win: circleci/windows@1.0.0

jobs:
  # pecl builds
  php-71:
    docker:
      - image: circleci/php:7.1
    environment:
      TYPE: "pecl"
    <<: *job-template

  php-71-zts:
    docker:
      - image: circleci/php:7.1-zts
    environment:
      TYPE: "pecl"
    <<: *job-template

  php-72:
    docker:
      - image: circleci/php:7.2
    environment:
      TYPE: "pecl"
    <<: *job-template

  php-72-zts:
    docker:
      - image: circleci/php:7.2-zts
    environment:
      TYPE: "pecl"
    <<: *job-template

  php-73:
    docker:
      - image: circleci/php:7.3
    environment:
      TYPE: "pecl"
    <<: *job-template

  php-73-zts:
    docker:
      - image: circleci/php:7.3-zts
    environment:
      TYPE: "pecl"
    <<: *job-template

  php-74:
    docker:
      - image: circleci/php:7.4
    environment:
      TYPE: "pecl"
    <<: *job-template

  php-74-zts:
    docker:
      - image: circleci/php:7.4-zts
    environment:
      TYPE: "pecl"
    <<: *job-template

  # git builds
  php-71-git:
    docker:
      - image: circleci/php:7.1
    environment:
      TYPE: "git"
    <<: *job-template

  php-71-zts-git:
    docker:
      - image: circleci/php:7.1-zts
    environment:
      TYPE: "git"
    <<: *job-template

  php-72-git:
    docker:
      - image: circleci/php:7.2
    environment:
      TYPE: "git"
    <<: *job-template

  php-72-zts-git:
    docker:
      - image: circleci/php:7.2-zts
    environment:
      TYPE: "git"
    <<: *job-template

  php-73-git:
    docker:
      - image: circleci/php:7.3
    environment:
      TYPE: "git"
    <<: *job-template

  php-73-zts-git:
    docker:
      - image: circleci/php:7.3-zts
    environment:
      TYPE: "git"
    <<: *job-template

  php-74-git:
    docker:
      - image: circleci/php:7.4
    environment:
      TYPE: "git"
    <<: *job-template

  php-74-zts-git:
    docker:
      - image: circleci/php:7.4-zts
    environment:
      TYPE: "git"
    <<: *job-template

  # windows builds
  php-win:
    executor: win/default
    environment:
      PHP_TYPE: "nts"
      TYPE: "pecl"
    <<: *job-template-win

  php-zts-win:
    executor: win/default
    environment:
      PHP_TYPE: "ts"
      TYPE: "pecl"
    <<: *job-template-win
    

workflows:
  version: 2
  tests:
    jobs:
      - php-7.1
      - php-7.1-zts
      - php-7.2
      - php-7.2-zts
      - php-7.3
      - php-7.3-zts
      - php-7.4
      - php-7.4-zts
      - php-7.1-git
      - php-7.1-zts-git
      - php-7.2-git
      - php-7.2-zts-git
      - php-7.3-git
      - php-7.3-zts-git
      - php-7.4-git
      - php-7.4-zts-git
